sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt -qq update && sudo apt install g++-6 libglew-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - wget https://github.com/eigenteam/eigen-git-mirror/archive/master.zip -O eigen.zip && unzip eigen.zip
  - mkdir -p eigen-git-mirror-master/build && cd eigen-git-mirror-master/build && cmake .. && make -j && sudo make install && cd ../..
  - wget https://github.com/stevenlovegrove/Pangolin/archive/master.zip -O Pangolin.zip && unzip Pangolin.zip
  - mkdir -p Pangolin-master/build && cd Pangolin-master/build && cmake .. && make -j && sudo make install && cd ../..

language: cpp

compiler:
  - gcc

os:
  - linux

env:
  - BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j
